### ISSUE TITLE
warnings during 'npm install' build

### ISSUE THREAD

**Issue by phybersyko** [goontube/goontube#1]
* npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
* npm WARN prefer global coffee-script@1.9.3 should be installed with -g
* npm WARN prefer global node-gyp@3.2.1 should be installed with -g
* npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
* npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6

**Comment by jskz** [comment]
We will revisit system specific dependencies and GreenKeeper soon.
