### ISSUE TITLE
Web form bug report by phybersyko - [video]

### ISSUE THREAD

**Issue by jskz** [goontube/goontube#12]
Dailymotion auto-playback appears to be bugged in Alpha. User must press 'play'.

Test vid: http://www.dailymotion.com/video/x4nnfs2

**Comment by phybersyko** [comment]
Appears to be tied to old Flash plugin. Disable or Uninstall flash from chrome:
chrome://plugins > Adobe Flash Player > DISABLE.
(Location may look like:
C:\Users\yourUser\AppData\Local\Google\Chrome\User Data\PepperFlash\22.0.0.209\pepflashplayer.dll)
